language: php
php:
 - 7.3.5
services:
  - postgresql
  - php bin/console doctrine:schema:create --dump-sql
  - php bin/console doctrine:migrations:diff 
  - php bin/console doctrine:migrations:migrate
  - php bin/console doctrine:fixtures:load
  - y
  
install :
  - composer install

