language: php
php:
 - 7.3.5

before_script:
  - composer install

services:
  - postgresql

# deploy: 
#   run:
#   - "php bin/console doctrine:migrations:migrate"
#   - "php bin/console doctrine:fixtures:load"
#   - "y"


